### ISSUE TITLE
NameError: name 'MaxAttemptedException' is not defined

### ISSUE THREAD

**Issue by spyhunter1280** [taoshidev/time-series-prediction-subnet#10]
I tried with staging and testnet
But same error occured everytime.

![image](https://github.com/taoshidev/time-series-prediction-subnet/assets/142394469/ee561912-9a07-43ff-8b64-3c4d0ec72b73)

![Screenshot 2023-11-21 135103](https://github.com/taoshidev/time-series-prediction-subnet/assets/142394469/041aa6f9-2a78-4994-9c6e-eb7cd4ebb835)

**Comment by taoshidev1** [comment]
This is an issue with testnet, and its a known issue. Please voice in general bittensor discord channel
