### ISSUE TITLE
Onboarding instructions for miners step 4 issue

### ISSUE THREAD

**Issue by pleaseshutup** [taoshidev/time-series-prediction-subnet#50]
Readme says for step 4 in running a miner:

> 
> Edit template/init.py
> 
> Edit the default NETUID=8 and CHAIN_ENDPOINT=wss://entrypoint-finney.opentensor.ai:443 arguments to match your created subnetwork.
> 
> Or run the miner and validator directly with the netuid and chain_endpoint arguments.

Issue is that template/init.py does not exist and template/__init__.py does not have NETUID or CHAIN_ENDPOINT settings.
The example command to run the miner directly with the command does not include the chain endpoint argument which should look like:

`python neurons/miner.py --netuid 8 --subtensor.chain_endpoint wss://entrypoint-finney.opentensor.ai:443 --wallet.name wallet_name --wallet.hotkey hotkey_name --logging.debug`

**Comment by TaoshiKen** [comment]
Thanks for the issue we will update!
